<a href="https://colab.research.google.com/github/thimotyb/real-world-machine-learning/blob/python3/Using_Pickle_and_Flask_for_ML_models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
# Taking the iris dataset to train a KNN as example
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing
import seaborn as sns
from sklearn import datasets

In [21]:
# Just to look at the full original data
train_path = "https://raw.githubusercontent.com/thimotyb/real-world-machine-learning/python3/data/Iris.csv"
train = pd.read_csv(train_path)
train.head(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [13]:
# LOading them split from sklearn dataset
X, y = datasets.load_iris(return_X_y=True)

In [15]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [20]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [16]:
X.shape, y.shape

((150, 4), (150,))

In [17]:
# NOw we use scikit to split/test/train and create the model
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=0)

In [18]:
X_train.shape, y_train.shape

((90, 4), (90,))

In [19]:
X_test.shape, y_test.shape

((60, 4), (60,))

In [22]:
# Fit and score the model
from sklearn import svm
clf = svm.SVC(kernel='linear', C=1).fit(X_train, y_train)
clf.score(X_test, y_test)

0.9666666666666667

In [25]:
 # Now you can use the trained model to predict, e.g. something similar at the 1st observation should yield 0 = Setosa
 clf.predict([[5.1, 3.4, 1.3, 0.2]])

array([0])

How can we actually bring the trained model  attained at the notebook in local system or colab to the flask environment? That’s where Pickle comes.

In [27]:
# Serialize the python object containing the model
import pickle
filename='model.pkl'
pickle.dump(clf, open(filename, 'wb'))

In [37]:
# Prepare the interface for the Flask application
import os

# Create templates dir if not exists
dir="templates"
if not os.path.exists(dir):
    os.mkdir(dir)

## Main form for input
index = """<html>
<body>
    <h3>Iris Species Classification</h3>
<div>
  <form action="/predict" method="POST">
    <label for="seplen">Sepal Length</label>
    <input type="number" step="0.01" id="seplen" name="seplen">
    <br>
    <label for="sepwid">Sepal Width</label>
    <input type="number" step="0.01" id="sepwid" name="sepwid">
    <br>
    <label for="petlen">Petal Length</label>
    <input type="number" step="0.01" id="petlen" name="petlen">
    <br>
    <label for="petwid">Petal Width</label>
    <input type="number" step="0.01" id="petwid" name="petwid">
    <br>
    <input type="submit" value="Submit">
  </form>
</div>
</body>
</html>
"""
with open('templates/index.html', 'w') as f:
  f.write(index)

## Template for response prediction
prediction="""<!doctype html>
<html>
   <body>
       <h1> {{ prediction }}</h1>
   </body>
</html>
"""
with open('templates/predict.html', 'w') as f:
  f.write(prediction)

In [ ]:
# Prepare Flask environment (in jupyter just for didactical reason, usually create a standalone app!)
!pip install flask-ngrok
from flask import Flask
from flask_ngrok import run_with_ngrok
app = Flask(__name__)
# ngrok tunnelling
run_with_ngrok(app)   

In [ ]:
# Create routes
@app.route(‘/’)
def index():
 return flask.render_template('index.html')

def ValuePredictor(to_predict_list):
 to_predict = np.array(to_predict_list).reshape(1,4)
 # Re-hydrate pickle model to perform prediction
 loaded_model = pickle.load(open('model.pkl','rb'))
 result = loaded_model.predict(to_predict)
 return result[0]

@app.route('/predict',methods = ['POST'])
def result():
 if request.method == 'POST':
 to_predict_list = request.form.to_dict()
 to_predict_list=list(to_predict_list.values())
 to_predict_list = list(map(float, to_predict_list))
 result = ValuePredictor(to_predict_list)
 prediction = str(result)
 return render_template("predict.html",prediction=prediction)

In [ ]:
# Run Flask app
app.run()